INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add user', 4, 'add_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change user', 4, 'change_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete user', 4, 'delete_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can view user', 4, 'view_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can add content type', 5, 'add_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can change content type', 5, 'change_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can delete content type', 5, 'delete_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can view content type', 5, 'view_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can add session', 6, 'add_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can change session', 6, 'change_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can delete session', 6, 'delete_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can view session', 6, 'view_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add book', 7, 'add_book');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change book', 7, 'change_book');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete book', 7, 'delete_book');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can view book', 7, 'view_book');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can add application', 8, 'add_application');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can change application', 8, 'change_application');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can delete application', 8, 'delete_application');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can view application', 8, 'view_application');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can add access token', 9, 'add_accesstoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can change access token', 9, 'change_accesstoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can delete access token', 9, 'delete_accesstoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can view access token', 9, 'view_accesstoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add grant', 10, 'add_grant');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change grant', 10, 'change_grant');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete grant', 10, 'delete_grant');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can view grant', 10, 'view_grant');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can add refresh token', 11, 'add_refreshtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can change refresh token', 11, 'change_refreshtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can delete refresh token', 11, 'delete_refreshtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can view refresh token', 11, 'view_refreshtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can add cors model', 12, 'add_corsmodel');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can change cors model', 12, 'change_corsmodel');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can delete cors model', 12, 'delete_corsmodel');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can view cors model', 12, 'view_corsmodel');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can add site', 13, 'add_site');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can change site', 13, 'change_site');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can delete site', 13, 'delete_site');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (52, 'Can view site', 13, 'view_site');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (53, 'Can add email address', 14, 'add_emailaddress');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (54, 'Can change email address', 14, 'change_emailaddress');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (55, 'Can delete email address', 14, 'delete_emailaddress');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (56, 'Can view email address', 14, 'view_emailaddress');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (57, 'Can add email confirmation', 15, 'add_emailconfirmation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (58, 'Can change email confirmation', 15, 'change_emailconfirmation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (59, 'Can delete email confirmation', 15, 'delete_emailconfirmation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (60, 'Can view email confirmation', 15, 'view_emailconfirmation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (61, 'Can add social account', 16, 'add_socialaccount');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (62, 'Can change social account', 16, 'change_socialaccount');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (63, 'Can delete social account', 16, 'delete_socialaccount');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (64, 'Can view social account', 16, 'view_socialaccount');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (65, 'Can add social application', 17, 'add_socialapp');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (66, 'Can change social application', 17, 'change_socialapp');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (67, 'Can delete social application', 17, 'delete_socialapp');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (68, 'Can view social application', 17, 'view_socialapp');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (69, 'Can add social application token', 18, 'add_socialtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (70, 'Can change social application token', 18, 'change_socialtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (71, 'Can delete social application token', 18, 'delete_socialtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (72, 'Can view social application token', 18, 'view_socialtoken');